### ISSUE TITLE
How does this work exactly?

### ISSUE THREAD

**Issue by acatangiu** [serban300/merge_snap#1]
Reading the code looks like `diff` is page-by-page copied over `base`. What happens when reading _a hole_ (I expected we'd get zeroes)? Why does the program [write the data read from a hole_ to `base`](https://github.com/serban300/merge_snap/blob/dca418bfb21b060272db735778634409b6abe7ae/src/main.rs#L45)?

**Comment by serban300** [comment]
The code should simply iterate over all the pages containing data from the `diff` file and write them over `base`. There might be corner cases, I haven't done a lot of tests, but only the actual data should be copied since `seek_data` jumps over holes.

https://man7.org/linux/man-pages/man2/lseek.2.html:
```
       SEEK_DATA
              Adjust the file offset to the next location in the file
              greater than or equal to offset containing data.  If
              offset points to data, then the file offset is set to
              offset.
```

**Comment by acatangiu** [comment]
Ok, I get it!

```rust
while let Some(seek_pos) = diff_file.seek_data(offset).unwrap()
```

will provide in `seek_pos` the _first offset/position where there is data_ starting from `offset`, like you say, effectively jumping over holes.

Thanks for the clarification!
